#!/bin/bash
#DIRECTORY=$(dirname "$0")
#echo "Changing to ${DIRECTORY}"
#cd  "$DIRECTORY" || exit 1

echo "Run your project here."
#get the arguments as a string and pass to main.py
#DNS challenge
python project/main.py dns01 --dir https://localhost:14000/dir --record 127.0.0.1 --domain localhost #--domain localhost
#HTTP challenge
#python project/main.py http01 --dir https://127.0.0.1:14000/dir --record 127.0.0.1 --domain localhost #--domain localhost


#just pass the arguments to main.py
#spython project/main.py "$@"
